package com.jairrab.presentation.models

import com.jairrab.domain.model.MapPoint
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Suppress("EXPERIMENTAL_API_USAGE")
@Serializable
data class Features(
    val mapPoints: List<MapPoint>
) {

    fun toJson(): String {
        //Notice we call a serializer method which is autogenerated from our class
        //once we have added the annotation to it
        return Json.stringify(serializer(), this)
    }
}